// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eTickets.Entities.DbContexts;

#nullable disable

namespace eTickets.Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorName = "Robert Downey Jr.",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "RobertDowneyJr.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ActorName = "Chris Evans",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "ChrisEvans.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ActorName = "Scarlett Johansson",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "ScarlettJohansson.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ActorName = "Leonardo DiCaprio",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "LeonardoDiCaprio.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ActorName = "Tom Hanks",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "TomHanks.jpg"
                        },
                        new
                        {
                            Id = 6,
                            ActorName = "Brad Pitt",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "BradPitt.jpg"
                        },
                        new
                        {
                            Id = 7,
                            ActorName = "Johnny Depp",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "JohnnyDepp.jpg"
                        },
                        new
                        {
                            Id = 8,
                            ActorName = "Denzel Washington",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "DenzelWashington.jpg"
                        },
                        new
                        {
                            Id = 9,
                            ActorName = "Meryl Streep",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MerylStreep.jpg"
                        },
                        new
                        {
                            Id = 10,
                            ActorName = "Morgan Freeman",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MorganFreeman.jpg"
                        },
                        new
                        {
                            Id = 11,
                            ActorName = "Tom Cruise",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "TomCruise.jpg"
                        },
                        new
                        {
                            Id = 12,
                            ActorName = "Jennifer Lawrence",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "JenniferLawrence.jpg"
                        },
                        new
                        {
                            Id = 13,
                            ActorName = "Will Smith",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "WillSmith.jpg"
                        },
                        new
                        {
                            Id = 14,
                            ActorName = "Christian Bale",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "ChristianBale.jpg"
                        },
                        new
                        {
                            Id = 15,
                            ActorName = "Natalie Portman",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "NataliePortman.jpg"
                        },
                        new
                        {
                            Id = 16,
                            ActorName = "Hugh Jackman",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "HughJackman.jpg"
                        },
                        new
                        {
                            Id = 17,
                            ActorName = "Emma Watson",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "EmmaWatson.jpg"
                        },
                        new
                        {
                            Id = 18,
                            ActorName = "Matthew McConaughey",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MatthewMcConaughey.jpg"
                        },
                        new
                        {
                            Id = 19,
                            ActorName = "Angelina Jolie",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "AngelinaJolie.jpg"
                        },
                        new
                        {
                            Id = 20,
                            ActorName = "Ryan Reynolds",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "RyanReynolds.jpg"
                        },
                        new
                        {
                            Id = 21,
                            ActorName = "George Clooney",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "GeorgeClooney.jpg"
                        },
                        new
                        {
                            Id = 22,
                            ActorName = "Julia Roberts",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "JuliaRoberts.jpg"
                        },
                        new
                        {
                            Id = 23,
                            ActorName = "Matt Damon",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MattDamon.jpg"
                        },
                        new
                        {
                            Id = 24,
                            ActorName = "Keanu Reeves",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "KeanuReeves.jpg"
                        },
                        new
                        {
                            Id = 25,
                            ActorName = "Charlize Theron",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "CharlizeTheron.jpg"
                        },
                        new
                        {
                            Id = 26,
                            ActorName = "Anne Hathaway",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "AnneHathaway.jpg"
                        },
                        new
                        {
                            Id = 27,
                            ActorName = "Harrison Ford",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "HarrisonFord.jpg"
                        },
                        new
                        {
                            Id = 28,
                            ActorName = "Chris Hemsworth",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "ChrisHemsworth.jpg"
                        },
                        new
                        {
                            Id = 29,
                            ActorName = "Robert De Niro",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "RobertDeNiro.jpg"
                        },
                        new
                        {
                            Id = 30,
                            ActorName = "Al Pacino",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "AlPacino.jpg"
                        },
                        new
                        {
                            Id = 31,
                            ActorName = "Zendaya",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "Zendaya.jpg"
                        },
                        new
                        {
                            Id = 32,
                            ActorName = "Timothée Chalamet",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "TimothéeChalamet.jpg"
                        },
                        new
                        {
                            Id = 33,
                            ActorName = "Tom Holland",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "TomHolland.jpg"
                        },
                        new
                        {
                            Id = 34,
                            ActorName = "Emma Stone",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "EmmaStone.jpg"
                        },
                        new
                        {
                            Id = 35,
                            ActorName = "Margot Robbie",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MargotRobbie.jpg"
                        },
                        new
                        {
                            Id = 36,
                            ActorName = "Ryan Gosling",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "RyanGosling.jpg"
                        },
                        new
                        {
                            Id = 37,
                            ActorName = "Daisy Ridley",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "DaisyRidley.jpg"
                        },
                        new
                        {
                            Id = 38,
                            ActorName = "Adam Driver",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "AdamDriver.jpg"
                        },
                        new
                        {
                            Id = 39,
                            ActorName = "John Boyega",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "JohnBoyega.jpg"
                        },
                        new
                        {
                            Id = 40,
                            ActorName = "Oscar Isaac",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "OscarIsaac.jpg"
                        },
                        new
                        {
                            Id = 41,
                            ActorName = "Benedict Cumberbatch",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "BenedictCumberbatch.jpg"
                        },
                        new
                        {
                            Id = 42,
                            ActorName = "Rami Malek",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "RamiMalek.jpg"
                        },
                        new
                        {
                            Id = 43,
                            ActorName = "Jason Momoa",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "JasonMomoa.jpg"
                        },
                        new
                        {
                            Id = 44,
                            ActorName = "Zac Efron",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "ZacEfron.jpg"
                        },
                        new
                        {
                            Id = 45,
                            ActorName = "Shailene Woodley",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "ShaileneWoodley.jpg"
                        },
                        new
                        {
                            Id = 46,
                            ActorName = "Idris Elba",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "IdrisElba.jpg"
                        },
                        new
                        {
                            Id = 47,
                            ActorName = "Rebecca Ferguson",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "RebeccaFerguson.jpg"
                        },
                        new
                        {
                            Id = 48,
                            ActorName = "Emily Blunt",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "EmilyBlunt.jpg"
                        },
                        new
                        {
                            Id = 49,
                            ActorName = "Paul Rudd",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "PaulRudd.jpg"
                        },
                        new
                        {
                            Id = 50,
                            ActorName = "Mila Kunis",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MilaKunis.jpg"
                        },
                        new
                        {
                            Id = 51,
                            ActorName = "Gal Gadot",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "GalGadot.jpg"
                        },
                        new
                        {
                            Id = 52,
                            ActorName = "Anya Taylor-Joy",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "AnyaTaylorJoy.jpg"
                        },
                        new
                        {
                            Id = 53,
                            ActorName = "Michael Fassbender",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MichaelFassbender.jpg"
                        },
                        new
                        {
                            Id = 54,
                            ActorName = "Tessa Thompson",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "TessaThompson.jpg"
                        },
                        new
                        {
                            Id = 55,
                            ActorName = "Jared Leto",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "JaredLeto.jpg"
                        },
                        new
                        {
                            Id = 56,
                            ActorName = "Eiza González",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "EizaGonzález.jpg"
                        },
                        new
                        {
                            Id = 57,
                            ActorName = "Elizabeth Debicki",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "ElizabethDebicki.jpg"
                        },
                        new
                        {
                            Id = 58,
                            ActorName = "Tom Hardy",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "TomHardy.jpg"
                        },
                        new
                        {
                            Id = 59,
                            ActorName = "Mads Mikkelsen",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MadsMikkelsen.jpg"
                        },
                        new
                        {
                            Id = 60,
                            ActorName = "Xolo Mariduena",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "XoloMariduena.jpg"
                        },
                        new
                        {
                            Id = 61,
                            ActorName = "Liam Cunningham",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "LiamCunningham.jpg"
                        },
                        new
                        {
                            Id = 62,
                            ActorName = "Jason Statham",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "JasonStatham.jpg"
                        },
                        new
                        {
                            Id = 63,
                            ActorName = "Orlando Bloom",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "OrlandoBloom.jpg"
                        },
                        new
                        {
                            Id = 64,
                            ActorName = "Mark Wahlberg ",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MarkWahlberg.jpg"
                        },
                        new
                        {
                            Id = 65,
                            ActorName = "Storm Reid",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "StormReid.jpg"
                        },
                        new
                        {
                            Id = 66,
                            ActorName = "Megan Suri",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "MeganSuri.jpg"
                        },
                        new
                        {
                            Id = 67,
                            ActorName = "Leslie Odom Jr.",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "LeslieOdomJr.jpg"
                        },
                        new
                        {
                            Id = 68,
                            ActorName = "Pete Davidson",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "PeteDavidson.jpg"
                        },
                        new
                        {
                            Id = 69,
                            ActorName = "John Cena",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "JohnCena.jpg"
                        },
                        new
                        {
                            Id = 70,
                            ActorName = "Kristen Bell",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhotoUrl = "KristenBell.jpg"
                        });
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Action",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Drama",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Comedy",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Horror",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Sci-Fi",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Romance",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Adventure",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Fantasy",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Thriller",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Documentary",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Family",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Animation",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Blu Ray",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "Cartoons",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CategoryName = "Mystery",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CategoryName = "Indian",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CategoryName = "Musical",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CategoryName = "Crime",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CategoryName = "Psychological",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CategoryName = "War",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CategoryName = "Historical",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In a vibrant and colorful world, Barbie sets off on a journey of self-discovery and adventure.",
                            Duration = 114,
                            MovieName = "Barbie",
                            PhotoUrl = "barbie.jpg",
                            ReleaseDate = new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A gripping biographical drama about J. Robert Oppenheimer and the development of the atomic bomb.",
                            Duration = 180,
                            MovieName = "Oppenheimer",
                            PhotoUrl = "oppenheimer.jpg",
                            ReleaseDate = new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Teenage Mutant Ninja Turtles return in an all-new animated adventure.",
                            Duration = 99,
                            MovieName = "Teenage Mutant Ninja Turtles: Mutant Mayhem",
                            PhotoUrl = "tmnt_mutant_mayhem.jpg",
                            ReleaseDate = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A single mother and her son enlist the help of a diverse group of experts to rid their home of supernatural inhabitants.",
                            Duration = 123,
                            MovieName = "Haunted Mansion",
                            PhotoUrl = "haunted_mansion.jpg",
                            ReleaseDate = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A young man becomes the Blue Beetle, a superhero powered by an alien scarab that grants him incredible abilities.",
                            Duration = 127,
                            MovieName = "Blue Beetle",
                            PhotoUrl = "blue_beetle.jpg",
                            ReleaseDate = new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A chilling horror tale based on the story of the ship that brought Dracula to England.",
                            Duration = 118,
                            MovieName = "The Last Voyage of the Demeter",
                            PhotoUrl = "demeter.jpg",
                            ReleaseDate = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A deep-sea thriller where a team of explorers must face a new and terrifying underwater threat.",
                            Duration = 116,
                            MovieName = "Meg 2: The Trench",
                            PhotoUrl = "meg_2.jpg",
                            ReleaseDate = new DateTime(2024, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Based on the true story of a gamer who becomes a professional race car driver through the Gran Turismo gaming franchise.",
                            Duration = 135,
                            MovieName = "Gran Turismo",
                            PhotoUrl = "gran_turismo.jpg",
                            ReleaseDate = new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A raunchy comedy where a group of stray dogs team up to get revenge on their owners.",
                            Duration = 93,
                            MovieName = "Strays",
                            PhotoUrl = "strays.jpg",
                            ReleaseDate = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The demonic nun returns to terrorize a new group of unsuspecting victims.",
                            Duration = 110,
                            MovieName = "The Nun II",
                            PhotoUrl = "nun_2.jpg",
                            ReleaseDate = new DateTime(2024, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Robert McCall returns to dispense justice in his own unique way.",
                            Duration = 108,
                            MovieName = "The Equalizer 3",
                            PhotoUrl = "equalizer_3.jpg",
                            ReleaseDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A horror film about a young girl who must confront a malevolent entity from her culture's folklore.",
                            Duration = 95,
                            MovieName = "It Lives Inside",
                            PhotoUrl = "it_lives_inside.jpg",
                            ReleaseDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A continuation of the iconic Exorcist saga, exploring new cases of possession.",
                            Duration = 120,
                            MovieName = "The Exorcist: Believer",
                            PhotoUrl = "exorcist_believer.jpg",
                            ReleaseDate = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comedic drama based on the true story of the GameStop stock phenomenon.",
                            Duration = 104,
                            MovieName = "Dumb Money",
                            PhotoUrl = "dumb_money.jpg",
                            ReleaseDate = new DateTime(2024, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Paw Patrol pups return in an action-packed adventure where they gain new superpowers.",
                            Duration = 88,
                            MovieName = "Paw Patrol: The Mighty Movie",
                            PhotoUrl = "paw_patrol.jpg",
                            ReleaseDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The iconic horror franchise returns with another mind-bending chapter of traps and terror.",
                            Duration = 105,
                            MovieName = "Saw X",
                            PhotoUrl = "saw_x.jpg",
                            ReleaseDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Captain Marvel teams up with Ms. Marvel and Monica Rambeau to face a new cosmic threat.",
                            Duration = 124,
                            MovieName = "The Marvels",
                            PhotoUrl = "the_marvels.jpg",
                            ReleaseDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A true-crime drama about the Osage murders and the birth of the FBI.",
                            Duration = 206,
                            MovieName = "Killers of the Flower Moon",
                            PhotoUrl = "killers_of_the_flower_moon.jpg",
                            ReleaseDate = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A horror film adaptation of the popular video game series where animatronics come to life with deadly intent.",
                            Duration = 102,
                            MovieName = "Five Nights at Freddy’s",
                            PhotoUrl = "five_nights_at_freddys.jpg",
                            ReleaseDate = new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A historical epic that chronicles the rise and fall of Napoleon Bonaparte.",
                            Duration = 157,
                            MovieName = "Napoleon",
                            PhotoUrl = "napoleon.jpg",
                            ReleaseDate = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A biographical film about Ronald Reagan's journey from Hollywood actor to the President of the United States.",
                            Duration = 98,
                            MovieName = "Reagan",
                            PhotoUrl = "reagan.jpg",
                            ReleaseDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A musical drama set in a prison where inmates find redemption through song and dance.",
                            Duration = 96,
                            MovieName = "Sing Sing",
                            PhotoUrl = "sing_sing.jpg",
                            ReleaseDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A suspenseful war thriller where soldiers must navigate deadly mind games in a high-stakes battle.",
                            Duration = 101,
                            MovieName = "War Game",
                            PhotoUrl = "war_game.jpg",
                            ReleaseDate = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sandy Cheeks leads a mission to save Bikini Bottom from an environmental disaster.",
                            Duration = 90,
                            MovieName = "Saving Bikini Bottom: The Sandy Cheeks Movie",
                            PhotoUrl = "sandy_cheeks.jpg",
                            ReleaseDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A political thriller about a journalist who uncovers a plot to overthrow a government.",
                            Duration = 112,
                            MovieName = "Coup!",
                            PhotoUrl = "coup.jpg",
                            ReleaseDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A captivating story that combines the mystery of dark feathers with the elegance of a geisha dance.",
                            Duration = 115,
                            MovieName = "Dark Feathers: Dance Of The Geisha",
                            PhotoUrl = "dark_feathers.jpg",
                            ReleaseDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A drama that follows the life of Rob Peace, exploring themes of struggle and redemption.",
                            Duration = 130,
                            MovieName = "Rob Peace",
                            PhotoUrl = "rob_peace.jpg",
                            ReleaseDate = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The minions are back for more mischief and adventure in the latest installment of the Despicable Me series.",
                            Duration = 90,
                            MovieName = "Despicable Me 4",
                            PhotoUrl = "despicable_me_4.jpg",
                            ReleaseDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A heartwarming tale set in a picturesque valley, focusing on personal growth and romance.",
                            Duration = 108,
                            MovieName = "Valleyheart",
                            PhotoUrl = "valleyheart.jpg",
                            ReleaseDate = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A high-octane action film featuring a race against time and relentless pursuit.",
                            Duration = 100,
                            MovieName = "One Fast Move",
                            PhotoUrl = "one_fast_move.jpg",
                            ReleaseDate = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A psychological thriller that delves into the mind of a man with an unsettling obsession.",
                            Duration = 105,
                            MovieName = "Cuckoo",
                            PhotoUrl = "cuckoo.jpg",
                            ReleaseDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A dramatic love story that explores the impact of a toxic relationship and personal growth.",
                            Duration = 120,
                            MovieName = "It Ends With Us",
                            PhotoUrl = "it_ends_with_us.jpg",
                            ReleaseDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The latest entry in the Alien franchise, focusing on a new planet and fresh horrors.",
                            Duration = 125,
                            MovieName = "Alien: Romulus",
                            PhotoUrl = "alien_romulus.jpg",
                            ReleaseDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A touching romance that explores the complexities of love and relationships.",
                            Duration = 110,
                            MovieName = "Close To You",
                            PhotoUrl = "close_to_you.jpg",
                            ReleaseDate = new DateTime(2024, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A dark and atmospheric film about revenge and redemption, inspired by the classic tale.",
                            Duration = 98,
                            MovieName = "The Crow",
                            PhotoUrl = "the_crow.jpg",
                            ReleaseDate = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A suspenseful thriller where every blink might reveal a hidden truth.",
                            Duration = 102,
                            MovieName = "Blink Twice",
                            PhotoUrl = "blink_twice.jpg",
                            ReleaseDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An inspiring story of faith and perseverance in the face of overwhelming odds.",
                            Duration = 116,
                            MovieName = "You Gotta Believe",
                            PhotoUrl = "you_gotta_believe.jpg",
                            ReleaseDate = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comedic and heartfelt look at the life of a retiree who finds unexpected adventure.",
                            Duration = 125,
                            MovieName = "The Retirement Plan",
                            PhotoUrl = "retirement_plan.jpg",
                            ReleaseDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A chilling ghost story set in the picturesque city of Venice.",
                            Duration = 120,
                            MovieName = "A Haunting in Venice",
                            PhotoUrl = "haunting_venice.jpg",
                            ReleaseDate = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A romantic comedy about the magic of falling in love unexpectedly.",
                            Duration = 105,
                            MovieName = "Love at First Sight",
                            PhotoUrl = "love_at_first_sight.jpg",
                            ReleaseDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.MovieActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorId = 35,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActorId = 36,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActorId = 48,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActorId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2
                        },
                        new
                        {
                            Id = 6,
                            ActorId = 23,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2
                        },
                        new
                        {
                            Id = 8,
                            ActorId = 31,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3
                        },
                        new
                        {
                            Id = 9,
                            ActorId = 69,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3
                        },
                        new
                        {
                            Id = 10,
                            ActorId = 55,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 4
                        },
                        new
                        {
                            Id = 11,
                            ActorId = 60,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 5
                        },
                        new
                        {
                            Id = 12,
                            ActorId = 61,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 6
                        },
                        new
                        {
                            Id = 13,
                            ActorId = 62,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 7
                        },
                        new
                        {
                            Id = 14,
                            ActorId = 63,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 8
                        },
                        new
                        {
                            Id = 15,
                            ActorId = 64,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 9
                        },
                        new
                        {
                            Id = 16,
                            ActorId = 65,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 10
                        });
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.MovieCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 4
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 4
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 5
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 5
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 6
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 19,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 6
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 7
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 7
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 8
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 8
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 9
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 10
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 11
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 11
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 12
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 12
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 13
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 14
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 18,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 14
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 15
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 15
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 16
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 19,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 16
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 17
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 17
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 18
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 18
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 19
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 20
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 21
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 21
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 17,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 22
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 22
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 23
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 23
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 24
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 24
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 25
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 18,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 25
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 26
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 7,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 26
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 27
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 28
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 28
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 29
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 30
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 31
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 19,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 31
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 32
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 32
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 33
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 33
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 34
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 35
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 35
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 36
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 36
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 37
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 38
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 38
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 39
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 39
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 40
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 40
                        });
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.MovieActor", b =>
                {
                    b.HasOne("eTickets.Entities.Model.Concrete.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTickets.Entities.Model.Concrete.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.MovieCategory", b =>
                {
                    b.HasOne("eTickets.Entities.Model.Concrete.Category", "Category")
                        .WithMany("MovieCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eTickets.Entities.Model.Concrete.Movie", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.Category", b =>
                {
                    b.Navigation("MovieCategories");
                });

            modelBuilder.Entity("eTickets.Entities.Model.Concrete.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
